#+TITLE: Projects

Following is a list of projects I am currently working on, or have
worked on in the past. Where possible, I have included links to the
Github repository, published/unpublished papers and the project
website.

The project website can be consulted to get a broad overview of the
project whilst the papers can be read if one wishes for more depth on
the matter. I usually host my projects on Github, the README can be
consulted to get familiar with the structure of the repository.

I am a strong proponent of open, reproducible research. To that
extent, where possible, I also link to my research logs. These logs
provide a granular look at the development of the projects. A word of
caution: these logs are not intended to be read in a top-down fashion.
They are simply there to serve as reference to those curious gain an
insight into scientific research.

* [2020] KM3NeT
  /Python, Pytorch, Pytorch Geometric/

  I collaborated with [[https://www.esciencecenter.nl/][The Netherlands eScience Center]] and [[https://www.nikhef.nl/en/][Nikhef]] to
  improve the data processing pipeline of the [[https://www.km3net.org][KM3NeT Neutrino
  Telescope]] using Graph Convolutional Neural Networks.

  [[[https://github.com/arumoy-shome/km3net][Github]]][[[file:assets/pdf/thesis-optimized.pdf][Paper]]]

* [2020] Privacy Preserving Deep Learning for Medical Imaging
  /Latex/
  
  I conducted a systematic literature review of deep learning systems
  that are inherently privacy preserving in nature. Practical
  applications include applying deep learning to sensitive data
  such as patient records from medical institutes.

  [[[file:assets/pdf/ppdl.pdf][Paper]]]

* [2020] vim-zettel
  /Vimscript/

  A (neo)vim plugin to manage plain text notes, inspired by Niklas
  Luhmann's [[https://en.wikipedia.org/wiki/Zettelkasten][Zettelkasten]] technique.
  
  [[[https://github.com/arumoy-shome/vim-zettel/][Github]]]
  
* [2020] vim-text-lists
  /Vimscript/

  A (neo)vim plugin that provides utility functions for working with
  plain text lists.

  [[[https://github.com/arumoy-shome/vim-text-lists][Github]]]
  
* [2019] ACE: Art, Color and Emotions
  /JavaScript, D3.js/
  
  We created a data driven, web based platform for exploring visual
  sentiment and emotion in artistic paintings over time. The project
  resulted in a demo paper which was published in ACM Multi
  Media 2019.

  [[[file:assets/pdf/ace-optimized.pdf][Paper]]][[[https://dl.acm.org/doi/abs/10.1145/3343031.3350588][Publication]]]

* TODO [2018] Metacognition

As a knowledge worker, I often like to reflect upon how I consume,
organize and retreat information. Much like our brain, this website is
intended to function as a web of interconnected ideas.

+ link to some relevant notes

* [2018] 3D Kadaster
  /Python, Apache Spark, Three.js/
  
  We created a 3D model of all the buildings in The Netherlands using
  point cloud dataset.

  [[[file:assets/pdf/kadaster-optimized.pdf][Paper]]][[[https://arumoy.me/3d-kadaster][Demo]]]

* [2018] Knowledge Acquisition from CommonCrawl
  /Python, NLTK, Stanford NLP/
  
  We applied a complete knowledge acquisition pipeline to WARC datasets
  using Natural Language Processing, Part of Speech tagging, Named
  Entity Recognition and Entity Linking. We also proposed a novel idea
  to improve entity retrieval using machine learning.

  [[[file:assets/pdf/wdp.pdf][Paper]]]

* [2017] Elevate
  /JavaScript, Phaser.io/

  We Collaborated with the Waterloo Regional Down Syndrome Society,
  Canada and Fundacion Paraiso Down, El Salvador to develop an improved
  and cheaper alternative to the state of the art cognitive assessment
  tool for individuals with Down Syndrome.

  [[[file:assets/pdf/elevate.pdf][Paper]]][[[https://github.com/arumoy-shome/elevate][Github]]][[[https://arumoy.me/elevate][Website]]]
